In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
from sklearn.datasets import load_iris

# Ejercicio 1

In [5]:
iris = load_iris()

In [6]:
data = iris.data

In [7]:
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [8]:
target = iris.target

In [9]:
feature_names = iris.feature_names

In [10]:
target_names = iris.target_names

In [11]:
sepal_length_index = feature_names.index("sepal length (cm)")
sepal_width_index = feature_names.index("sepal width (cm)")
petal_length_index = feature_names.index("petal length (cm)")
petal_width_index = feature_names.index("petal width (cm)")

In [12]:
sepal_length = data[:, sepal_length_index]
sepal_width = data[:, sepal_width_index]
petal_length = data[:, petal_length_index]
petal_width = data[:, petal_width_index]

In [13]:
feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [14]:
target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [15]:
target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Ejercicio 2

In [16]:
concat = np.concatenate((data, target.reshape(-1, 1)), axis=1)

In [17]:
concat[:5]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])

# Ejercicio 3

In [18]:
media_sepalos = round(np.mean(sepal_length), 2)

In [19]:
print ("La media de longitud de los sepalos es", media_sepalos, "cm")

La media de longitud de los sepalos es 5.84 cm


In [20]:
media_petalos = round(np.mean(petal_length), 2)

In [21]:
print ("La media de longitud de los petalos es", media_petalos, "cm")

La media de longitud de los petalos es 3.76 cm


In [22]:
print ("La desviación de los sepalos es de", round(np.std(sepal_length), 2), "cm")

La desviación de los sepalos es de 0.83 cm


In [23]:
print ("La desviación de los petalos es de", round(np.std(petal_length), 2), "cm")

La desviación de los petalos es de 1.76 cm


# Ejercicio 4

In [24]:
from numpy import random

In [25]:
np.random.choice(concat.shape[0], 20, replace=False)

array([136, 140,  65,  64,  93,  87,  97,   7,  71,  58,  54,  78, 135,
        98, 123,  83, 133,  86,  69, 103])

# Ejercicio 5

In [26]:
species_names = np.unique(iris.target_names)

mean_matrix = np.zeros((len(species_names), len(feature_names)))
std_matrix = np.zeros((len(species_names), len(feature_names)))

for i, species in enumerate(species_names):
    indices = (target == i)
    subset_data = data[indices, :]
    mean_matrix[i, :] = np.mean(subset_data, axis=0)
    std_matrix[i, :] = np.std(subset_data, axis=0)

print("Media de cada característica por especie:")
print(mean_matrix)

print("\nDesviación estándar de cada característica por especie:")
print(std_matrix)

Media de cada característica por especie:
[[5.006 3.428 1.462 0.246]
 [5.936 2.77  4.26  1.326]
 [6.588 2.974 5.552 2.026]]

Desviación estándar de cada característica por especie:
[[0.34894699 0.37525458 0.17191859 0.10432641]
 [0.51098337 0.31064449 0.46518813 0.19576517]
 [0.62948868 0.31925538 0.54634787 0.27188968]]


# Ejercicio 6

In [27]:
especies = iris.target_names[iris.target]

conteo_por_especie = np.unique(especies, return_counts=True)

print("Cantidad de muestras por especie:")
for tr, cantidad in zip(conteo_por_especie[0], conteo_por_especie[1]):
    print(f"{tr}: {cantidad}")

Cantidad de muestras por especie:
setosa: 50
versicolor: 50
virginica: 50


In [28]:
indice_max_promedio_petal_length = np.argmax(mean_matrix[:, petal_length_index])

In [29]:
print("La especie con los pétalos de mayor longitud es:", species_names[indice_max_promedio_petal_length])

La especie con los pétalos de mayor longitud es: virginica


# Ejercicio 7

In [30]:
print ("Matriz con correlación \n", np.corrcoef(concat, rowvar=False))

Matriz con correlación 
 [[ 1.         -0.11756978  0.87175378  0.81794113  0.78256123]
 [-0.11756978  1.         -0.4284401  -0.36612593 -0.42665756]
 [ 0.87175378 -0.4284401   1.          0.96286543  0.9490347 ]
 [ 0.81794113 -0.36612593  0.96286543  1.          0.95654733]
 [ 0.78256123 -0.42665756  0.9490347   0.95654733  1.        ]]


In [31]:
data[data[:, petal_length_index] > media_petalos]

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.4, 3.8, 1.1],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2

In [39]:
indice_petalos = np.argmax(data[:, petal_length_index])

In [40]:
print ("Los petalos más grandes de cada muestra", data[indice_petalos, :])

Los petalos más grandes de cada muestra [7.7 2.6 6.9 2.3]


# Ejercicio 8

In [34]:
diferencia_medias = np.abs(media_sepalos - media_petalos)

In [35]:
indice_especie_max_diferencia = np.argmax(diferencia_medias)

In [36]:
print("Especie con la mayor diferencia entre longitud media de sépalos y pétalos:", species_names[indice_especie_max_diferencia])

Especie con la mayor diferencia entre longitud media de sépalos y pétalos: setosa
